### ISSUE TITLE
Example at the end of the HTTP protocol binding specification is inconsistent with itself

### ISSUE THREAD

**Issue by JasonKeirstead** [TAXIIProject/TAXII-Specifications#81]
At the end of the HTTP protocol binding specification there are recommendations for the location of the discovery service - however, the example does not agree with the reccomendation in the sentence prior, which results in confusion (which is being recommended, path A or path B?)

-

Recommended Discovery Service Location

TAXII Servers offering one or more Discovery Services are recommended to use the following format to
determine the location of at least one discovery service:

**Discovery Service URL = "http://" + your domain + "/taxii-discovery-service/"**
**Example: http://example.com/TaxiiDiscoveryService/**

**Comment by MarkDavidson** [comment]
http://taxii.mitre.org/specifications/version1.1/TAXII_Errata_02July2014.pdf

That was the first mistake we noticed =)
